FROM debian
ADD debian.list /etc/apt/sources.list.d/
RUN apt-get update && apt-get -y upgrade && apt -y install nginx && apt-get clean && \
    cd /var/www/ && rm -rf ./* && \
    mkdir -p DariaUstina.com/img && \
    chmod -R 754 /var/www/DariaUstina.com/ && \
    useradd Daria && groupadd Ustina && usermod -aG Daria Ustina && \
    chown -R Daria:Ustina /var/www/DariaUstina.com/ && \
    sed -i 's/\/var\/www\/html/\/var\/www\/DariaUstina/g' /etc/nginx/sites-enabled/default && \
    sed -i 's/user www-data/user Daria/g' /etc/nginx/nginx.conf
ADD index.html /var/www/DariaUstina.com/
ADD img.jpg /var/www/DariaUstina.com/img/
CMD ["nginx", "-g", "daemon off;"]
